# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 329)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);\n"
"background-color: rgb(0, 85, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbDT = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbDT.setFont(font)
        self.lbDT.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbDT.setObjectName("lbDT")
        self.horizontalLayout.addWidget(self.lbDT)
        self.leDT = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leDT.setFont(font)
        self.leDT.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leDT.setObjectName("leDT")
        self.horizontalLayout.addWidget(self.leDT)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbWC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbWC.setFont(font)
        self.lbWC.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbWC.setObjectName("lbWC")
        self.horizontalLayout_2.addWidget(self.lbWC)
        self.leWC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leWC.setFont(font)
        self.leWC.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leWC.setObjectName("leWC")
        self.horizontalLayout_2.addWidget(self.leWC)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbWS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbWS.setFont(font)
        self.lbWS.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbWS.setObjectName("lbWS")
        self.horizontalLayout_3.addWidget(self.lbWS)
        self.leWS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leWS.setFont(font)
        self.leWS.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leWS.setObjectName("leWS")
        self.horizontalLayout_3.addWidget(self.leWS)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbH = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbH.setFont(font)
        self.lbH.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbH.setObjectName("lbH")
        self.horizontalLayout_4.addWidget(self.lbH)
        self.leH = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leH.setFont(font)
        self.leH.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leH.setObjectName("leH")
        self.horizontalLayout_4.addWidget(self.leH)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbT = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbT.setFont(font)
        self.lbT.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbT.setObjectName("lbT")
        self.horizontalLayout_5.addWidget(self.lbT)
        self.leT = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leT.setFont(font)
        self.leT.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leT.setObjectName("leT")
        self.horizontalLayout_5.addWidget(self.leT)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbC.setFont(font)
        self.lbC.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbC.setObjectName("lbC")
        self.horizontalLayout_6.addWidget(self.lbC)
        self.leC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leC.setFont(font)
        self.leC.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leC.setObjectName("leC")
        self.horizontalLayout_6.addWidget(self.leC)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbSTS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbSTS.setFont(font)
        self.lbSTS.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbSTS.setObjectName("lbSTS")
        self.horizontalLayout_7.addWidget(self.lbSTS)
        self.leSTS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leSTS.setFont(font)
        self.leSTS.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leSTS.setObjectName("leSTS")
        self.horizontalLayout_7.addWidget(self.leSTS)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbST10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbST10.setFont(font)
        self.lbST10.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbST10.setObjectName("lbST10")
        self.horizontalLayout_8.addWidget(self.lbST10)
        self.leST10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leST10.setFont(font)
        self.leST10.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leST10.setObjectName("leST10")
        self.horizontalLayout_8.addWidget(self.leST10)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbSM = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbSM.setFont(font)
        self.lbSM.setStyleSheet("background-color: rgb(238, 238, 0);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-color: rgb(107, 53, 80);")
        self.lbSM.setObjectName("lbSM")
        self.horizontalLayout_9.addWidget(self.lbSM)
        self.leSM = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.leSM.setFont(font)
        self.leSM.setStyleSheet("background-color: rgb(231, 124, 144);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:  rgb(238, 238, 0);\n"
"border-radius: 0px;")
        self.leSM.setObjectName("leSM")
        self.horizontalLayout_9.addWidget(self.leSM)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather and Field Soil Report App"))
        self.pushButton.setText(_translate("MainWindow", "Get Weather and Field Soil Report"))
        self.lbDT.setText(_translate("MainWindow", "Date & Time:"))
        self.leDT.setText(_translate("MainWindow", "DD-MM-YYYY HH:MM:SS"))
        self.lbWC.setText(_translate("MainWindow", "Weather Condition:"))
        self.leWC.setText(_translate("MainWindow", "None"))
        self.lbWS.setText(_translate("MainWindow", "Wind Speed:"))
        self.leWS.setText(_translate("MainWindow", "None"))
        self.lbH.setText(_translate("MainWindow", "Humidity:"))
        self.leH.setText(_translate("MainWindow", "None"))
        self.lbT.setText(_translate("MainWindow", "Temperature:"))
        self.leT.setText(_translate("MainWindow", "None"))
        self.lbC.setText(_translate("MainWindow", "Cloudiness:"))
        self.leC.setText(_translate("MainWindow", "None"))
        self.lbSTS.setText(_translate("MainWindow", "Surface Temp of Soil:"))
        self.leSTS.setText(_translate("MainWindow", "None"))
        self.lbST10.setText(_translate("MainWindow", "Soil Temp at 10cm of Depth:"))
        self.leST10.setText(_translate("MainWindow", "None"))
        self.lbSM.setText(_translate("MainWindow", "Soil Moisture:"))
        self.leSM.setText(_translate("MainWindow", "None"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
